apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prime-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: prime-app
  source:
    path: "HelmCharts/Mychart1"
    repoURL: "git@github.com:Amanbeq/argo_cd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: amanbeq/prime
        value: amaneq/prime
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

